version: '3.8'

services:
  dind:
    image: docker:dind
    privileged: true
    networks:
      jenkins:
        aliases:
          - docker
    volumes:
      - docker-certs-ca:/certs/ca
      - docker-certs-client:/certs/client
      - jenkins-data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock

  jenkins:
    image: jenkins/jenkins:lts-jdk11
    networks:
      - jenkins
    ports:
      - "8080:8080"
      - "50000:50000"
    environment:
      DOCKER_HOST: "tcp://docker:2376"
      DOCKER_CERT_PATH: /certs/client
      DOCKER_TLS_VERIFY: 1
    volumes:
      - docker-certs-client:/certs/client:ro
      - jenkins-data:/var/jenkins_home
      - /usr/bin/docker:/usr/bin/docker

networks:
  jenkins:

volumes:
  docker-certs-ca:
  docker-certs-client:
  jenkins-data:
